"""Render the CompSoc logo as half-block text for the hero's fastfetch-style output.

Each character cell covers two vertically stacked pixels: "▀" painted with the
top pixel's colour as foreground and the bottom one's as background. Output is
src/components/sections/Home/ascii-logo.ts (runs of cells with the same colours).

    python3 scripts/ascii-logo.py [cols]
"""
import json
import sys

from PIL import Image

COLS = int(sys.argv[1]) if len(sys.argv) > 1 else 28
src = Image.open("src/assets/img/compsoc/compsoc_logo.png").convert("RGBA")
src = src.crop(src.getbbox())
w, h = src.size
# A JetBrains Mono cell at line-height 1 is 0.6em x 1em, so each half-cell
# "pixel" is 0.6 x 0.5: 1.2 times wider than tall. Sample more rows to match.
PIXEL_ASPECT = 0.6 / 0.5
rows_px = round(COLS * PIXEL_ASPECT * h / w)
rows_px += rows_px % 2
img = src.resize((COLS, rows_px), Image.LANCZOS)


def cls(px):
    r, g, b, a = px
    if a < 110:
        return "_"
    if r > 170 and g > 170 and b > 170:
        return "f"  # white terminal
    return "a"  # accent hexagon


rows = []
for y in range(0, rows_px, 2):
    runs = []
    for x in range(COLS):
        top, bottom = cls(img.getpixel((x, y))), cls(img.getpixel((x, y + 1)))
        if top == bottom:
            cell = (" ", "_", "_") if top == "_" else ("█", top, "_")
        elif top == "_":
            cell = ("▄", bottom, "_")
        elif bottom == "_":
            cell = ("▀", top, "_")
        else:
            cell = ("▀", top, bottom)
        if runs and runs[-1][1:] == list(cell[1:]):
            runs[-1][0] += cell[0]
        else:
            runs.append(list(cell))
    # trailing blanks carry no information
    if runs and runs[-1][1] == "_" and runs[-1][2] == "_" and not runs[-1][0].strip():
        runs.pop()
    rows.append(runs)

with open("src/components/sections/Home/ascii-logo.ts", "w") as f:
    f.write(
        "// Generated by scripts/ascii-logo.py from compsoc_logo.png. Do not edit.\n"
        "// Each run is [text, foreground, background]: a = accent, f = foreground, _ = none.\n"
        f"export const ASCII_LOGO_COLS = {COLS}\n"
        "export const ASCII_LOGO: ReadonlyArray<ReadonlyArray<readonly [string, string, string]>> = "
        + json.dumps(rows, ensure_ascii=False)
        + "\n"
    )

for runs in rows:
    print("".join(t if fg != "f" else t.replace("█", "▓") for t, fg, bg in runs))
